#CONFIGURAÇÃO NO BANCO DE DADOS H2


spring:

 datasource:
   url: jdbc:h2:mem:dbevento
   username: root
   password: 
   driverClassName: org.h2.Driver

  
 jpa:
  database-plataform: org.hibernate.dialect.H2Dialect
  properties.hibernate.show_sql: true
  properties.hibernate.format_sql: true
  defer-datasource-initialization: true
  

 h2:
  console:
   enabled: true
   path: /eventoapp


#CONFIGURAÇÃO NO POSTGREESQL (Para poder Upar no HEROKU)


#spring:
#
# datasource:
#  url=${JDBC_DATASOURCE_URL}
#  driveClassName=org.postgresql.Driver
#  maxActive=10
#  maxIdle=5
#  minIdle=2
#  initialSize=5
#  removeAbandoned=true
#
# jpa:
#  show-sql=true
#  generate-dll=true
#
#  server.port=${PORT:8080}
